name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cdreate env file
      run: |
            echo "GITHUB_OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}"> app.env
            echo "GITHUB_OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET}}" >> app.env

    - name: Build images
      run: docker-compose build
      if: success()

    - name: Run tests
      run: ./runCompose.sh
      if: success()

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      if: success()

    - name: Push images to Docker Hub
      run: |
        docker push lhhung/nginx:test
        docker push lhhung/flask:compose
